require("dotenv").config();
const express=require("express"),cors=require("cors"),helmet=require("helmet"),crypto=require("crypto"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),Razorpay=require("razorpay"),{z}=require("zod"),{PrismaClient}=require("@prisma/client"),path=require("path");
const app=express(),prisma=new PrismaClient();
app.set("trust proxy",1); app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:true,credentials:true}));
function safeEqual(a,b){const x=Buffer.from(a||""),y=Buffer.from(b||"");return x.length===y.length&&crypto.timingSafeEqual(x,y)}
app.post("/api/payments/razorpay/webhook",express.raw({type:"application/json"}),async(req,res)=>{try{const secret=process.env.RAZORPAY_WEBHOOK_SECRET;if(!secret)return res.status(503).json({error:"Webhook secret not configured"});const sig=req.header("x-razorpay-signature")||"",exp=crypto.createHmac("sha256",secret).update(req.body).digest("hex");if(!safeEqual(sig,exp))return res.status(400).json({error:"Invalid signature"});const e=JSON.parse(req.body.toString("utf8")),p=e.payload?.payment?.entity;if(e.event==="payment.captured"&&p?.order_id){await creditPayment(p.order_id,p.id)}return res.json({ok:true})}catch(err){console.error(err);return res.status(400).json({error:"Invalid webhook"})}});
app.use(express.json({limit:"1mb"})); app.use(express.static(path.join(process.cwd(),"public")));
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace(/^Bearer /,""),process.env.JWT_SECRET);next()}catch{res.status(401).json({error:"Authentication required"})}}
function admin(req,res,next){if(req.user?.role!=="ADMIN")return res.status(403).json({error:"Admin only"});next()}
async function creditPayment(orderId,paymentId){return prisma.$transaction(async tx=>{const p=await tx.payment.findUnique({where:{razorpayOrderId:orderId}});if(!p)return null;if(p.status==="PAID")return p;const rate=Number(process.env.USD_PER_INR_RATE||0.011);const usd=Number(p.amountInr||0)*rate;await tx.payment.update({where:{id:p.id},data:{status:"PAID",razorpayPaymentId:paymentId,amountUsd:usd}});await tx.user.update({where:{id:p.userId},data:{balanceUsd:{increment:usd}}});return p})}
app.get("/api/health",(_,res)=>res.json({ok:true,service:"AI Compute Cloud"}));
app.post("/api/auth/register",async(req,res)=>{try{const b=z.object({name:z.string().min(2).max(80),email:z.string().email().max(160),password:z.string().min(8).max(128)}).parse(req.body),email=b.email.toLowerCase();if(await prisma.user.findUnique({where:{email}}))return res.status(409).json({error:"Email already registered"});const u=await prisma.user.create({data:{name:b.name,email,passwordHash:await bcrypt.hash(b.password,12)}});res.status(201).json({id:u.id,email:u.email})}catch{res.status(400).json({error:"Invalid registration data"})}});
app.post("/api/auth/login",async(req,res)=>{const b=z.object({email:z.string().email(),password:z.string()}).safeParse(req.body);if(!b.success)return res.status(400).json({error:"Invalid login"});const u=await prisma.user.findUnique({where:{email:b.data.email.toLowerCase()}});if(!u||!(await bcrypt.compare(b.data.password,u.passwordHash)))return res.status(401).json({error:"Invalid email or password"});res.json({token:jwt.sign({id:u.id,role:u.role,email:u.email},process.env.JWT_SECRET,{expiresIn:"7d"})})});
app.get("/api/gpus",async(_,res)=>res.json(await prisma.gpuProduct.findMany({where:{active:true},orderBy:{priceUsdPerHour:"asc"}})));
app.get("/api/me",auth,async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user.id},select:{id:true,name:true,email:true,role:true,balanceUsd:true,createdAt:true}})));
app.post("/api/payments/order",auth,async(req,res)=>{try{const {amountInr}=z.object({amountInr:z.number().int().min(100).max(1000000)}).parse(req.body);if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:"Payment gateway is not configured yet"});const rp=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}),receipt="acc_"+crypto.randomUUID();const o=await rp.orders.create({amount:amountInr*100,currency:"INR",receipt});await prisma.payment.create({data:{userId:req.user.id,amountInr,amountUsd:0,razorpayOrderId:o.id}});res.json({orderId:o.id,amount:o.amount,currency:o.currency,keyId:process.env.RAZORPAY_KEY_ID})}catch(e){console.error(e);res.status(400).json({error:"Could not create payment order"})}});
app.post("/api/payments/verify",auth,async(req,res)=>{try{const b=z.object({razorpay_order_id:z.string(),razorpay_payment_id:z.string(),razorpay_signature:z.string()}).parse(req.body);const exp=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET||"").update(b.razorpay_order_id+"|"+b.razorpay_payment_id).digest("hex");if(!safeEqual(exp,b.razorpay_signature))return res.status(400).json({error:"Invalid payment signature"});const p=await prisma.payment.findFirst({where:{razorpayOrderId:b.razorpay_order_id,userId:req.user.id}});if(!p)return res.status(404).json({error:"Payment not found"});await creditPayment(b.razorpay_order_id,b.razorpay_payment_id);res.json({ok:true})}catch(e){console.error(e);res.status(400).json({error:"Payment verification failed"})}});
app.post("/api/jobs",auth,async(req,res)=>{try{const b=z.object({gpuProductId:z.string(),requestedHours:z.number().positive().max(Number(process.env.MAX_JOB_HOURS||12))}).parse(req.body),gpu=await prisma.gpuProduct.findUnique({where:{id:b.gpuProductId}});if(!gpu||!gpu.active)return res.status(404).json({error:"GPU unavailable"});const cost=Number(gpu.priceUsdPerHour)*b.requestedHours,user=await prisma.user.findUnique({where:{id:req.user.id}});if(Number(user.balanceUsd)<cost)return res.status(402).json({error:"Insufficient balance. Add funds first.",estimatedCostUsd:cost});const job=await prisma.$transaction(async tx=>{const fresh=await tx.user.findUnique({where:{id:user.id}});if(Number(fresh.balanceUsd)<cost)throw new Error("INSUFFICIENT");await tx.user.update({where:{id:user.id},data:{balanceUsd:{decrement:cost}}});return tx.job.create({data:{userId:user.id,gpuProductId:gpu.id,requestedHours:b.requestedHours,estimatedCostUsd:cost,status:"PENDING"}})});res.status(201).json({job,message:"Job recorded. Provider provisioning will start only after the approved RunPod integration is configured."})}catch(e){res.status(e.message==="INSUFFICIENT"?402:400).json({error:e.message==="INSUFFICIENT"?"Insufficient balance.":"Invalid job request"})}});
app.get("/api/jobs",auth,async(req,res)=>res.json(await prisma.job.findMany({where:{userId:req.user.id},include:{gpuProduct:true},orderBy:{createdAt:"desc"}})));
app.get("/api/admin/summary",auth,admin,async(_,res)=>{const [users,jobs,payments,gpus]=await Promise.all([prisma.user.count(),prisma.job.count(),prisma.payment.aggregate({_sum:{amountInr:true}}),prisma.gpuProduct.count({where:{active:true}})]);res.json({users,jobs,paymentsInr:payments._sum.amountInr||0,activeGpuProducts:gpus})});
app.get(/.*/,(_,res)=>res.sendFile(path.join(process.cwd(),"public","index.html")));
const port=Number(process.env.PORT||8080);app.listen(port,()=>console.log("AI Compute Cloud listening on "+port));